### ISSUE TITLE
Multiple ipfilters do not work

### ISSUE THREAD

**Issue by Merccy** [pyed/ipfilter#11]
I tried to setup multiple IP filters using the following code

`# Only allow my home computer to connect
ipfilter / {
    rule allow
    ip ...
}
# Allow bitbucket to use webhook
ipfilter /webhook_site {
    rule allow
    ip 131.103.20.0-255 165.254.145.0-255 104.192.143.0-255
}`

It appears that only the last filter is used and the first one is truncated.

I hope this is not the intended behavior.

**Comment by pyed** [comment]
only one ipfilter block can be used currently, it probably should show an error when more than one block is defined in the config.

I will look into allowing more than one block to be defined, but I know it will be complicated to get it right, PRs are always welcome 😉

**Comment by Merccy** [comment]
How I would imagine it working, store all filters in a list.

Sort this list by the length of the scope so the scope '/' will be found first.

Then basically add another foreach loop at line 133 to iterate over the stored configs instead of a single config and keep a boolean allow that is set to true, when it finds a filter it should store the result in that boolean.
Because the list of configurations is stored by scope this should work in all instances that I can imagine.

I might try to make a PR but I am really new to Go and Caddy.

**Comment by pyed** [comment]
that what I had in mind, I will give it a shot soon.
