### ISSUE TITLE
Feature Request: CIDR Ranges

### ISSUE THREAD

**Issue by shellster** [pyed/ipfilter#14]
Hi, 

Would it be possible to add support for CIDR ranges?

It appears that Go actually has a native CIDR range parser (example of use here): https://gist.github.com/kotakanbe/d3059af990252ba89a82

You might ask why I would want this.  A couple of reasons come to mind.  First, it is sometimes tidier than the options currently supported.  Also, a lot of my websites are actually front-ended by Cloudflare.  Ideally I don't want anyone to be able to access my sites directly.  IPFilter is one way to accomplish this.  Cloudflare gives me a list of IP ranges in CIDR format that their servers run from:
https://www.cloudflare.com/ips-v4

I could manually parse those out, but what if they change?  It'd be nice to write a simple script to scrape the page and regularly apply the changes to my Caddy config.

**Comment by pyed** [comment]
it's been requested a couple of times, I will take a look into it soon.

**Comment by pyed** [comment]
There's a new branch [CIDR](https://github.com/pyed/ipfilter/tree/cidr) it moved the code from `Ranges` to `CIDR` as the main and the recommended way of specifying a range, I wanted it to be also backward compatible, so all the old ranges will get converted to CIDR using `ranges2CIDR.go` I'm not 100% sure if that's the best way to do it, but it is sure better than breaking everyone's config.

Also it should support IPv6 but I haven't tested it yet, as it uses `net.ParseCIDR` and `net.IPNet.Contains` now.

I converted the tests and they all pass, but I would like to get more people to test and review the changes.

@fboyer @Magnifisite

**Comment by pyed** [comment]
`ipfilter` now support CIDR and IPv6 https://github.com/pyed/ipfilter/commit/64efabf5475d984587fdad1f91d45cc6f3c9a2ef
