### ISSUE TITLE
Filter on ::1 gives a parse error 

### ISSUE THREAD

**Issue by mwpastore** [pyed/ipfilter#17]
Attempting to filter on ::1 gives the following error:

```
Parse error: ipfilter: Can't parse IPv4 address
```

I've tried the following combinations of statements, which all yield the same result:

```
ip 127.0.0.1 ::1
```

```
ip 127.0.0.1
ip ::1
```

```
ip 127.0.0.1
ip 0:0:0:0:0:0:0:1
```

```
ip ::1
```

```
ip 0:0:0:0:0:0:0:1
```

**Comment by pyed** [comment]
you are using an old version of `ipfilter`, I see that `caddyserver.com` is still including an older version of `ipfilter` with `Caddy 0.9.4`, @mholt should be able to fix that.

**Comment by mholt** [comment]
Yeah... as soon as I can get around to it. The new website is almost ready for testing, I just gotta finish up some design work so that's where most of my time is right now :-/ but it will allow you to deploy your plugin whenever you want. :smile:

**Comment by mwpastore** [comment]
I built Caddy from source and this filter works great now! Thank you.

**Comment by mholt** [comment]
I just updated the build server.

**Comment by pyed** [comment]
Thank you @mholt

**Comment by mholt** [comment]
Sorry for the delay. 😅
