### ISSUE TITLE
Load a file with ips

### ISSUE THREAD

**Issue by navossoc** [pyed/ipfilter#22]
Hi, is it possible to load a file with a IPs list to avoid clutter in my caddyfile?

Something like the GeoLite database, but only with the IPs I want to block/allow.

**Comment by krader1961** [comment]
I don't think this should be implemented. It is way too expensive and doesn't scale. Do you really want your web server to have to load a file that may be a megabyte or larger in size just to blacklist some addresses? How should the server deal with changes to the blacklist file? Obviously loading it on every request is silly. But even just reloading the file only if the last modification timestamp has changed is going to be expensive. It makes more sense to use a dynamic data store such as SQLite. Or, as I've suggested in issue #29, simply store the IP addresses as entries in the file system namespace.

**Comment by krader1961** [comment]
> I think that querying the file system to check if a file exists on every access to block some IP will be more expensive than load and query the entries on memory.

Yes, but the difference is inconsequential. On my system calling `stat()` on a non-existent path in a directory that is in the filesystem cache takes ~5 microseconds. That is going to be the common case.

> I was not suggesting to create something new here, just the ability to import the rules from an external file

Caddy already provides that capability using the `import` directive. So if manually forcing a reload by sending SIGUSR1 is acceptable then this feature is already implemented.

P.S., When you exclude private addresses (e.g., 192.168.0.1) you're left with approximately 3.7 billion public IPv4 addresses. Back of the napkin calculation says that would take ~34 GB to enumerate them all in a file. Blacklisting 300k addresses would require a file ~3 MB in size.

**Comment by navossoc** [comment]
> Yes, but the difference is inconsequential. On my system calling stat() on a non-existent path in a directory that is in the filesystem cache takes ~5 microseconds. That is going to be the common case.

I'm assuming you are talking about a local file system right?
Not sure how scalable is this approach either.

Anyway...
