### ISSUE TITLE
filtering by fqdn?

### ISSUE THREAD

**Issue by hijak** [pyed/ipfilter#23]
Hi

I know if kinda defeats the point of calling it ipfilter but im looking for something similar to filter based on hostnames as im using ddns and am unable to whitelist via ip

any suggestions :)

**Comment by krader1961** [comment]
This enhancement request needs more information. Under what conditions do you control the web server and client but need to delegate resolution of names to IP addresses to a third-party?

**Comment by krader1961** [comment]
Also, once my change for issue #30 is merged you could solve this by using the `prefix_dir` subdirective it introduces. Then create a program that uses `dig` or some other means of converting hostnames to IP addresses and create files whose names are those addresses. Periodically run the program to keep the whitelist up to date. Alternatively, if you know you DDNS entry has changed "push" the updates to the whitelist `prefix_dir`.

**Comment by krader1961** [comment]
@pyed It seems like this can be closed. The `prefix_dir` filesystem based enumeration of IP addrs feature should make it possible for @hijak to implement this feature without requiring Caddy+ipfilter to do RDNS lookups on every request.
