### ISSUE TITLE
support exception paths? 

### ISSUE THREAD

**Issue by zhentianxincun** [pyed/ipfilter#26]
Support exception paths. More flexible.

example.com {
  root /var/www/html
  ipfilter /a {
    rule allow
    ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
    not /a/b
  }
}

**Comment by krader1961** [comment]
This feature isn't needed AFAICT. Isn't is sufficient to place a more specific `ipfilter /a/b` block before the `ipfilter /a` block? I've only been using Caddy plus this plugin for a couple of weeks so perhaps I'm missing some reason that solution isn't viable. If so I am happy to hear someone tell me I don't know what I'm talking about.

Note that it might be necessary to put the `ipfilter /a/b` block after the `ipfilter /a` block. I'm still learning about the rules regarding order of precedence for such situations. But one of those solutions should do the same thing without needing to introduce "exception paths".

**Comment by pyed** [comment]
> Isn't is sufficient to place a more specific `ipfilter /a/b` block before the `ipfilter /a` block?
