### ISSUE TITLE
Content Type not set when gzip middleware is enabled

### ISSUE THREAD

**Issue by jonesnc** [pyed/ipfilter#28]
I'll quote [this post made by Matthew Fay on the Caddy support forum](https://caddy.community/t/caddy-ipfilter-downfile-not-getting-served-when-gzip-is-enabled-browser-downloads-it-instead/4076) here, since I'm not really familiar with this codebase:

> The gzip directive operates early on in the middleware chain, but it simply swaps out the default ResponseWriter for a gzipWriter so anything written by later middleware such as ipfilter is compressed.
> 
> If you take a look at [the ipfilter code handling blocked pages](https://github.com/pyed/ipfilter/blob/6b25e48ff3eef8d894f6fca240463f726ee7f7eb/ipfilter.go#L57-L75), it doesn’t look like a Content-Type header is set anywhere when the nominated block page is written. For an example of code that sets the Content-Type while returning a nominated HTML document, see [this code in the built-in errors plugin 1](https://github.com/mholt/caddy/blob/053373a38519d8cdf4ee7582ed9dc6ce239597cc/caddyhttp/errors/errors.go#L89-L92).
> 
> When a browser receives a compressed file without a content type, it can’t make the assumption that it’s HTML intended to be rendered, so it downloads it instead. I’d wager that’s the cause of your problem.
>

**Comment by pyed** [comment]
I applied the suggested fix with no success, I will look into it later.

**Comment by pyed** [comment]
Fixed, thank you for reporting
