### ISSUE TITLE
Issue filtering IPs

### ISSUE THREAD

**Issue by fboyer** [pyed/ipfilter#3]
Hi,

Just to give you some context on my setup, I have an Apache server sitting in the DMZ as a SSL termination point to proxy the requests to the internal caddy server.

So I'm running into an issue with the ipfilter middleware which does not seem to respect the "allow" rule that is defined in my Caddyfile:

```
:80
gzip
log /var/log/caddy/access.log {
  rotate {
    size 100
    age  14
    keep 10
  }
}
ipfilter / {
  rule allow
  ip   192.168.34.1 10.252.60.0-255
}
root /apps/caddy/www/
tls off
```

Just to give you some context on my setup, I have an Apache server sitting in the DMZ as a SSL termination point to proxy the requests to the internal caddy server.

Basically any requests coming from the proxy are identified as 192.168.34.1 in the access.log and the 10.252.60.0-255 is to allow internal IPs accessing the server directly.

Here is the access.log:
```
<snip>
10.252.60.53 - [10/Dec/2015:09:19:05 -0500] "GET /buildroot/ HTTP/1.1" 200 37
10.252.60.53 - [10/Dec/2015:09:19:24 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:19:56 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:19:59 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:20:01 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:20:22 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:21:11 -0500] "GET /buildroot/ HTTP/1.1" 304 0
192.168.34.1 - [10/Dec/2015:09:21:17 -0500] "GET /buildroot/ HTTP/1.1" 403 37
10.252.60.53 - [10/Dec/2015:09:56:02 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:56:04 -0500] "GET /buildroot/ HTTP/1.1" 304 0
192.168.34.1 - [10/Dec/2015:09:56:06 -0500] "GET /buildroot/ HTTP/1.1" 403 37
192.168.34.1 - [10/Dec/2015:09:56:08 -0500] "GET /buildroot/ HTTP/1.1" 403 37
192.168.34.1 - [10/Dec/2015:09:56:36 -0500] "GET /buildroot/ HTTP/1.1" 403 37
10.252.60.53 - [10/Dec/2015:09:56:40 -0500] "GET /buildroot/ HTTP/1.1" 304 0
10.252.60.53 - [10/Dec/2015:09:59:07 -0500] "GET /buildroot/ HTTP/1.1" 304 0
192.168.34.1 - [10/Dec/2015:09:59:11 -0500] "GET /buildroot/ HTTP/1.1" 403 37
```

Do you have any idea what could be causing this issue?

Thanks!

**Comment by fboyer** [comment]
I forgot to mention what the log basically shows is that anything coming from an internal IP is allowed but requests coming from the proxy are 403'ed.

**Comment by fboyer** [comment]
Additional information, if I remove the "ipfilter" from my Caddyfile:
```
:80
gzip
log /apps/caddy/logs/access.log {
  rotate {
    size 100
    age  14
    keep 10
  }
}
root /apps/caddy/www/
tls off
```

Everything works:
```
10.252.60.53 - [10/Dec/2015:11:58:27 -0500] "GET /buildroot/ HTTP/1.1" 304 0
192.168.34.1 - [10/Dec/2015:11:58:31 -0500] "GET /buildroot/ HTTP/1.1" 200 37
```

**Comment by fboyer** [comment]
So I think I've figured out the cause of this issue following a bit more investigation but I can't say I've resolved it.

First of all, even though the logs report that the request is coming from 192.168.34.1, it's actually coming from the proxy server which has the internal IP 192.168.34.84. 192.168.34.1 is actually the vlan gateway.

Now, the **main** issue is that the IPs being logged in the caddy access.log file are not the actual IPs being filtered by the ipfilter middleware. I found out that if I put anything but the proxy server IP (192.168.34.84), then nothing will work but if I put the proxy server IP (192.168.34.84) then everything will work.

If you are following my reasoning then you should now understand that the ipfilter middleware is not able to filter out anything.

Caddyfile:
```
:80
gzip
log /apps/caddy/logs/access.log {
  rotate {
    size 100 # Rotate after 100 MB
    age  14  # Keep log files for 14 days
    keep 10  # Keep at most 10 log files
  }
}
ipfilter / {
  rule allow
  ip   192.168.34.84
}
root /apps/caddy/www/
tls off
```

access.log:
```
<snip>
192.168.34.1 - [10/Dec/2015:14:05:54 -0500] "GET /buildroot/ HTTP/1.1" 200 37
184.151.114.49 - [10/Dec/2015:14:06:06 -0500] "GET /buildroot/ HTTP/1.1" 200 37
```

**Comment by fboyer** [comment]
Confirmed that caddy logs are using "X-Forwarded-For" otherwise "remote ip" which is why there was a difference between what was logged and what was actually happening.

The ipfilter middleware probably only filters out on "remote ip" which would explain everything and why it is not working when behind a proxy.

**Suggestion**: 
It would be probably be interesting to add a config option to enable different way to filter IPs, such as "strictly X-Forwarded-For", "X-Forwarded-For, otherwise remote ip" and "strictly remote ip". It could perhaps default to the "X-Forwarded-For, otherwise remote ip" which would be in line with what can be seen in the logs but that could be seen as a "breaking change" to a certain extent so it could also default to "strictly remote ip" if you want to remain on the safe side.

(Or, instead of all of this, it could simply be enabling a "proxy mode" which would apply the "X-Forwarded-For, otherwise remote ip" mode)

**Comment by pyed** [comment]
your findings are right, ipfilter was originally designed to filter only by country codes, which means only remote ip, your suggestion should be added eventually, I would be glad to get a PR though ;)
