### ISSUE TITLE
Require a `rule` directive

### ISSUE THREAD

**Issue by krader1961** [pyed/ipfilter#31]
While working on the implementation of the `prefix_dir` directive I noticed that it isn't an error if no `rule` directive is provided and it defaults to `rule allow`. I'd like to propose requiring an explicit `rule` directive in every ipfilter block. I also think we should treat more than one as an error since that almost certainly indicates the user has made a configuration mistake; e.g., trying to put both allow and block rules in the same block.

**Comment by pyed** [comment]
I agree. I’m on a trip ATM. Planning on releasing version 1.1.0 when i go back with the new prefix_dir feature. It would be great if you made a PR with this fix.
