### ISSUE TITLE
Leverage placeholders from geoip plugin

### ISSUE THREAD

**Issue by krader1961** [pyed/ipfilter#34]
I'm using both this and the [geoip](https://github.com/kodnaplakal/caddy-geoip) middleware plugin. It would be nice if this plugin had a way to utilize the country code placeholder `caddy-geoip` adds to the request . context. That would avoid the need to do this lookup more than once. The obvious solution is to add something like a `geoip_cc_name <country_code_placeholder_name>` directive. Which would be used instead of a `database` directive and instruct ipfilter to use the named placeholder value.

**Comment by pyed** [comment]
Do you think it is worth it to add more complexity to the code and the docs just to leverage a very specific case where the user uses `geoip` and wants to filter using country code just to save the extra database lookup which is pretty cheap (isn't it?), would be nice if the code was originally written to work with the `geoip` plugin to filter based on country codes instead dealing the `MaxMind` directly, but I guess it's too late now.

**Comment by krader1961** [comment]
You're right. This optimization doesn't appear to be warranted. I added some instrumentation and the lookup took 13us the first time and 1us for subsequent lookups of the same IP addr. Not exactly a robust benchmark but those quick and dirty results suggest there would be negligible benefit. Certainly not enough to justify the added complexity. Sorry for the noise.

**Comment by pyed** [comment]
Thank you for your great contributions.
