### ISSUE TITLE
How do mutiple ipfilter blocks handle query strings?

### ISSUE THREAD

**Issue by notastudio** [pyed/ipfilter#38]
My server is running a WordPress site. I don't want anyone except me to access the login page `/wp-login.php`, but allow everyone access `/wp-login.php?action=postpass`. Here is my config:
```
 ipfilter /wp-login.php {
         rule allow
         ip [MY_IP_ADDRESS]
 }
 ipfilter /wp-login.php?action=postpass {
         rule block
         ip 8.8.8.8
 }
```
However, it doesn't work. `/wp-login.php?action=postpass` is also blocked. So what should I do? Thanks a lot!

**Comment by pyed** [comment]
`ipfilter` doesn't care about query -and it shouldn't- only paths matter.
