### ISSUE TITLE
Range and Single IP's don't work together.

### ISSUE THREAD

**Issue by dragon2611** [pyed/ipfilter#7]
Orginally posted on the caddy Github but was pointed to here, 

if you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!

1. What version of Caddy are you running (caddy -version)?

0.82

2. What are you trying to do?

Add both single IP's and ranges to IP filter as per documentation.

3. What is your entire Caddyfile?

Do not wish to provide.

However to reproduce create an IP filter and list multiple IP's with some ranges e.g

ipfilter /mydirectory {
rule allow
ip 192.168.1.1 10.0.0.3 10.0.17.0-254 10.0.24.0-255
}

4. How did you run Caddy (give the full command and describe the execution environment)?

N/A

5. What did you expect to see?

All traffic from listed IP's allowed

6. What did you see instead (give full error messages and/or log)?

Traffic sourced from an IP within the defined Ranges appears to be allowed, however traffic sourced from one of the individual IP's listed is NOT allowed, If you remove the Ranges from the config then the single IP's are then granted access.

**Comment by pyed** [comment]
will look into it when i get home, which will take ~5 days.

**Comment by pyed** [comment]
sorry about the late response, this issue actually doesn't exist with ipfilter, but `caddyserver.com` is providing an old version of ipfilter that has it, @mholt will probably fix it soon.

**Comment by pyed** [comment]
it is fixed now, you can download a new version from caddyserver.com with `ipfilter`, and it should work as expected.
